export const RECORD_NOT_FOUND = "RECORD_NOT_FOUND";
export const RECORD_WITH_UNIQUE_FIELD_ALREADY_EXIST =
    "RECORD_WITH_UNIQUE_FIELD_ALREADY_EXIST";
export const INVALID_WHERE_ARGS = "INVALID_WHERE_ARGS";